#coding:utf-8
"""
Django settings for r_blog project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k6h+5wq!xvcp3e32ryq^e0^^%3%ao%p-!zo(qy3h+qji&p1&(q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.cms',
    'api.common',
    'api.front',
    'article',
    'cms_auth',
    'front_auth'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'api.cms.middlewares.avatar_middleware',
    'front_auth.middlewares.front_user_middleware',
]

ROOT_URLCONF = 'r_blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': []
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'api.cms.context_processors.avatar_context_processor',
                'front_auth.context_processors.front_user_context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'r_blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'r_blog',
        'USER':'root',
        'PASSWORD':'2312231223',
        'HOST':'127.0.0.1',
        'PORT':3306,
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES={
    'default':{
        'BACKEND':'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION':[
            '127.0.0.1:11211',
        ]
    },
}

SESSION_ENGINE='django.contrib.sessions.backends.db'

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


SESSION_COOKIE_AGE=60*60*24*7*2

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

LOGIN_URL='/cms/login/'

# 七牛配置
QINIU_ACCESS_KEY='oYKZUfA-AkUu9fAB5pJ7nbWPcuMJ6y4JMJrnCmzv'

QINIU_SECRET_KEY='hU8FUVpl-UWMfjIVsy5bNjDh22jMbAlUXc_WdpB7'

BUCKET_NAME='rblog'

#邮件配置置
EMAIL_HOST_USER='657930342@qq.com'
EMAIL_HOST_PASSWORD='hggiofvfzgygbddb'

EMAIL_HOST='smtp.qq.com'
EMAIL_PORT='587'

EMAIL_USE_TLS=True

#分页配置
SINGLE_PAGE_NUM=15 #每页显示的文章数量
SHOW_PAGE=5         #每页显示的分页数量