# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-10 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='tag',
            new_name='tags',
        ),
    ]
