# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170811_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
