# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-11 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_topmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='top',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.TopModel'),
        ),
    ]
