# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-14 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20170814_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
