# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20170814_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='origin_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.CommentModel'),
        ),
    ]
