# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-09 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CMSUser',
            new_name='CMSUserModel',
        ),
    ]
